umip/.gitignore
umip/Makefile
umip/README.md
umip/umip_exceptions.c
umip/umip_test_defs.h
umip/umip_utils.c

UMIP(User-Mode Instruction Prevention) is a security feature in Intel Processors. If UMIP is enabled, it verifies that execution of the instructions(SGDT, SIDT, SLDT, SMSW, STR) should return a sinal SEGV(Segmentation Violation) or a dummy value if CPL(Current Privilege Level) is greater than 0.
Below instructions are protected by UMIP feature:
* SGDT - Store Global Descriptor Table
* SIDT - Store Interrupt Descriptor Table
* SLDT - Store Local Descriptor Table
* SMSW - Store Machine Status Word
* STR  - Store Task Register For the detailed information, please check the README.md in umip folder.

UMIP test: Initial version for UMIP test.

---

cet/shstk_huge_page.c
cet/test_shadow_stack.c
cet/wrss.c

Fix the compilation warning issues from CET test code.
Reported-by: Yi Sun <yi.sun@intel.com>

CET test: Fix the compilation warning issues

---

umip/umip_exceptions.c

Fix the compilation warning issue from umip_exceptions.c.

UMIP test: Fix the compilation warning issue

---

th/th_test.c

Add a header for function 'close'.
Replace 'strncpy' with 'memcpy'.
Remove an unnecessary declaration.

th: Fix the warning complaint that occurred during compilation.

---

common/common.sh

To leverage common shell library, developers need to source $LKVS_ROOT/common/common.sh at the top of their scripts. Users of lkvs need to export $LKVS_ROOT as appropriate before running any tests that written in shell scripts.

common/common.sh: import shell common library

---

cet/Makefile
cet/test_shadow_stack.c

Because the conflict of LAM and CET arch_prctl number, cet arch_prctl number will change from 0x400x to 0x500x.
And update the test code to match latest CET user space shstk kernel. Related new update kernel link:
https://lore.kernel.org/lkml/20221104223604.29615-25-rick.p.edgecombe@intel.com/

test_shadow_stack.c: update the test due to cet arch_prctl number change

---

cet/.gitignore
cet/Makefile
cet/shstk_unlock_test.c

Add user space shstk unlock test:
1. Test user space shstk enabling by syscall
2. Fork child prcess and child process should enable shstk also
3. Unlock child process by ptrace from parent process.
4. Get/set shstk regset test
5. Finally disable shstk test

shstk_unlock_test.c: add user space shstk unlock test

---

.env
common/common.sh

This patch provides a way to append all sub directories of lkvs projects to $PATH varible. It allows developers invoking shell scripts and binaries in lkvs project directly, rather than using absolute/relative path.
Usage:
add following code to the top of scripts
```shell
[[ -e "../.env" ]] && source "../.env"
```
Example:
```shell
#!/usr/bin/env bash
...
[[ -e "../.env" ]] && source "../.env"
source common.sh
...
test_print_trc "..."
...
```
Note: scripts and binaries with same names are not allowed in project scope!

common/common.sh: move PATH exporting to .env

---

.env

Summary of this commit:
1. fix functionality of adding all subdirectories to $PATH variable
2. import all resource from common.sh
Utilize .env file in 2 ways:
1. add following line to the top of any scripts that may be called from terminal directly(assume scripts are in next level of lkvs root directory):
```
$ cd "$(dirname $0)" 2> /dev/null; source ../env
```
2. source .env from terminal, then you can wrap any executables with the function `runtest`. It should be useful for developing new tests for lkvs.
```
$ runtest "<executables>"
```

.env: functionality fixing and enhancement

---

runtests

**runtests** is a test runner for running tests in lkvs with ease. It's totally **optional**, which means all tests in lkvs should be able to run without it.
There are 2 ways to pass test to **runtests**:
1. Pass test cmdline using `-c` option.
2. Write test cmdline in a file, then pass the file using `-f` option. We call the file cmdfile. A cmdfile can contain multiple tests.
Output of tests can be saved in a file using `-o` option.
Examples:
```
$ ./runtests -f <cmdfile>
$ ./runtests -f <cmdfile> -o <logfile>
$ ./runtests -c <cmdline>
$ ./runtests -c <cmdline> -o <logfile>
```

runtests: introduce a mini runner for lkvs

---

cet/Makefile
cet/wrss.c

Because the conflict of LAM and CET arch_prctl number, cet arch_prctl number will change from 0x400x to 0x500x.
And update the test code to match latest CET user space shstk kernel.

wrss.c: update the test due to cet arch_prctl number change

---

runtests

If one case is executed in subfolder, tester will know each case and dmesg clearly by "dmesg | tail" before the test. When tester uses runtests for bunch of tests, it's better to add LKVS test isolation in dmesg log.
If there is some "Call Trace" and so on bug, tester could know clearly that which case trigger the problem.

runtests: Add LKVS test isolation in dmesg log when use runtests

---

Dockerfile.build

Download latest code from github, then compile it locally.

Dockerfile: Install libipt in the docker image

---

cet/shstk_cp.c
cet/shstk_unlock_test.c

Fix the long and int type mismatch issue in shstk_cp.c and shstk_unlock_test.c.

cet: Fix the long and int type mismatch issue.

---

Makefile

Makefile will check whether the sub dir has a Makefile before enter it and try to do the compiling. The compiling will be interrupted if a single sub folder failed to compile.

Makefile: Bugfix: check Makefile existing before compile

---

cet/cet_tests.sh
cet/tests
cet_driver/Makefile

Add 2 kernel space IBT test cases:
It will load cet_driver/cet_ioctl.ko module for kernel space IBT tests. And use cet_app b1|b2 to do illegal indirect jump IBT and leagal indirect jump IBT tests.

cet: Add 2 kernel space IBT test cases

---

README.md
cet/.gitignore
cet/Makefile
cet/cet_driver/.gitignore
cet/cet_driver/Makefile
cet/cet_driver/cet_app.c
cet/cet_driver/cet_ioctl.c
cet/cet_driver/cet_ioctl.h
cet/cet_tests.sh
cet/tests

Add 2 kernel space IBT test cases:
It will load cet_driver/cet_ioctl.ko module for kernel space IBT tests.
1. "./cet_app b1" will execute illegal indirect jump IBT in kernel space and trigger "Missing ENDBR" BUG dmesg info and it means kernel IBT prevent the IBT violation as expected, and kernel space should not exist IBT violation and trigger "Missing ENDBR" issue, so kernel still reports this issue as BUG.
2. "./cet_app b2" will execute leagal indirect jump IBT in kernel space and should not trigger "Missing ENDBR" BUG dmesg info.

Kernel space IBT: add 2 kernel space IBT test cases

---

cet/README.md
cet/shstk_cp.c
cet/shstk_unlock_test.c
cet/test_shadow_stack.c
cet/wrss.c

The ARCH_SHSTK related features bits number doesn't change, but the name changes in latest user space shstk kernel code, so update them to keep them same.
Related latest user space shstk code patches link: https://lore.kernel.org/lkml/20230218211433.26859-35-rick.p.edgecombe@intel.com/

cet: update the ARCH_SHSTK bits name to match with latest kernel code

---

tdx-compliance/tdx-compliance-cpuid.h
tdx-compliance/tdx-compliance.c

According to the latest TDX v1.5 specifications, certain adjustments are required in some cases to prevent false failures.

Fixup: tdx-compliance: Fix some case due to the spec change.

---

tdx-compliance/tdx-compliance-cr.h

According to the latest TDX v1.5 specifications, certain adjustments are required in some cases and related pre-condition function to prevent false failures.

Fixup: tdx-compliance: Fix some cases and related pre-condition function.

---

cet/shstk_alloc.c
cet/shstk_cp.c
cet/shstk_huge_page.c
cet/shstk_unlock_test.c
cet/test_shadow_stack.c
cet/wrss.c

When compile in cet user space SHSTK kernel, /usr/include/asm/unistd.h or /usr/include/sys/syscall.h or /usr/include/asm/unistd_64.h will define __NR_map_shadow_stack syscall number, and will trigger below WARNING: "
warning: "__NR_map_shadow_stack" redefined
"#define __NR_map_shadow_stack 451"
"
Improve the __NR_map_shadow_stack definition to avoid the warning.

cet: improve __NR_map_shadow_stack definition to avoid the warning

---

.github/scripts/build_check
Dockerfile.build
Makefile

Pass the local /lib/modules folder to the docker for kernel cases compiling.

Dockerfile: Use native kernel headers when building Kernel module

---

tdx-compliance/tdx-compliance-cpuid.h

Some cpuid cases changed in latest tdx arch spec.

Modify CPUID test cases in tdx-compliance

---

cet/tests

Reported-by: Yi Sun <yi.sun@intel.com>

cet/tests: remove useless "./" for test automation

---

tdx-compliance/tdx-compliance-msr.h

All following MSR registers are reserved for now, remove them. RESERVED_0X0550_READ
RESERVED_0X0550_WRITE
RESERVED_0X1921_READ
RESERVED_0X1921_WRITE
RESERVED_0X1925_READ
RESERVED_0X1925_WRITE
RESERVED_0X1981_READ
RESERVED_0X1981_WRITE
RESERVED_0X09A0_READ
RESERVED_0X09A0_WRITE
RESERVED_0X09C0_READ
RESERVED_0X09C0_WRITE
RESERVED_0X09E0_READ
RESERVED_0X09E0_WRITE
RESERVED_0X09F0_READ
RESERVED_0X09F0_WRITE

tdx-compliance: remove reserve MSR registers check.

---

cet/cet_tests.sh

$1 is parsed as full path "/home/lijun/lkvs/cet/glibc_shstk_test" instead of the intended "glibc_shstk_test". So save it at "/home/lijun/lkvs/cet/glibc_shstk_test.txt" instead of "/tmp/glibc_shstk_test.txt"
Logs:
<<<test start - 'cet_tests.sh -t cet_ssp -n glibc_shstk_test -p ssp'>> |0822_170810.092|TRACE|Test bin:/home/lijun/lkvs/cet/glibc_shstk_test ssp, cet_ssp:check dmesg | |0822_170810.099|TRACE|Find bin:/home/lijun/lkvs/cet/glibc_shstk_test| |0822_170810.149|TRACE|recorded dmesg timestamp: 20899.763861| |0822_170810.159|TRACE|/home/lijun/lkvs/cet/glibc_shstk_test ssp| |0822_170811.275|TRACE|do_cmd() is called by cet_tests.sh:91:cet_shstk_check()| |0822_170811.279|TRACE|CMD=objdump -d /home/lijun/lkvs/cet/glibc_shstk_test > /tmp//home/lijun/lkvs/cet/glibc_shstk_test.txt| …

cet: change objdump output file location

---

cet/shstk_alloc.c
cet/shstk_cp.c
cet/shstk_huge_page.c
cet/shstk_unlock_test.c
cet/test_shadow_stack.c
cet/wrss.c

User space SHSTK has been merged into Linux kernel main line: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=df57721f9a63e8a1fb9b9b2e70de4aa4c7e0cd2e
SHSTK syscall map_shadow_stack number is 453(not 451 or 452) in Linux mainline kernel:
https://github.com/torvalds/linux/blob/0468be89b3fa5b9249cee1097f1d50314950a2df/arch/x86/entry/syscalls/syscall_64.tbl#L377 All test kernel will follow the main line kernel, so update map_shadow_stack to 453 for future kernel tests.

cet: update map_shadow_stack syscall number due to kernel code update

---

tools/Makefile
tools/cpuid_check/Makefile
tools/cpuid_check/cpuid_check.c

Add cpuid_check as a common tool to check cpuid.
It does not depend on any other package such as cpuid package and checks cpuid specific bit settings as expected.

tools: add cpuid check tool

---

guest-test/guest.test_launcher.sh

improve the logic of $GCOV handling to provide correct and clear VM status management

Test Enhance: improve logic regarding $GCOV handling

---

ifs/ifs_common.sh

In order to filter the correct sibling cpu list, fix the ALL_CPUS format in one line.

ifs_common.sh: fix the sibling cpu list issue

---

Makefile

Read proxy setting from following variables: https_proxy, HTTPS_PROXY, all_proxy and ALL_PROXY. If none of them is set, `--build-arg` will not be passed to `docker bulid` command.

Makefile: read proxy setting from multiple environment variables.

---

guest-test/guest.qemu_runner.sh
guest-test/guest.test_executor.sh
guest-test/guest.test_launcher.sh
guest-test/osv_sanity/qemu.config.default.json
guest-test/osv_sanity/qemu.config.tsc.json
guest-test/osv_sanity/tdx_guest_tsc_check.sh
guest-test/osv_sanity/tdx_host_tsc_check.sh
guest-test/osv_sanity/test_2.1.1.4
guest-test/qemu.config.json
guest-test/qemu_get_config.py

add testcase of TDX1.0 osv_sanity test_2.1.1.4 reference implementation

Guest test TDX1.0 OSV sanity test reference

---

common/kselftest.h
xsave/xstate.c

Refine the print of the result lines. And take xsave as a pilot case.

Refine format of result lines

---

guest-test/guest.test_executor.sh
guest-test/tdx/tdx.test_executor.sh
guest-test/tdx_osv_sanity/tdx_osv_sanity.test_executor.sh

guest-test/guest.test_executor.sh:16 - Quote this to prevent word splitting., refer to https://github.com/koalaman/shellcheck/wiki/SC2046 
guest-test/tdx/tdx.test_executor.sh:16 - Quote this to prevent word splitting., refer to https://github.com/koalaman/shellcheck/wiki/SC2046 
guest-test/tdx_osv_sanity/tdx_osv_sanity.test_executor.sh:16 - Quote this to prevent word splitting., refer to https://github.com/koalaman/shellcheck/wiki/SC2046
[Test Components] tdx

[guest-test] Code Check: revise based on SC2046

---

README.md
workload-xsave/work_AVX2.c
workload-xsave/work_AVX512.c
workload-xsave/work_DOTPROD.c
workload-xsave/work_VNNI.c
workload-xsave/work_VNNI512.c
workload-xsave/worker_init_avx2.c
workload-xsave/worker_init_dotprod.c
workload-xsave/yogini.c

Supplement the missing header files in the workload-xsave folder.Modify the yogini source file and output help when input is missing.

Supplementary header file

---

workload-xsave/CMakeLists.txt
workload-xsave/README.md
workload-xsave/yogini.h

1. Based on the instruction set supported by the CPU, selectively compile the source files.

[enhancement] workload-xsave: Add cmake build support

---

cet/cet_driver/cet_ioctl.c

class_create(const char *name) has no second parameter any more in v6.3-rc1: https://git.kernel.org/pub/scm/linux/kernel/git/torvalds/linux.git/commit/?id=dcfbb67e48a2becfce7990386e985b9c45098ee5 And it will cause the cet driver module to fail to compile, as follows: /root/lkvs/cet/cet_driver/cet_ioctl.c:166:14: error: too many arguments to function ‘class_create’
166 |         cl = class_create(THIS_MODULE, "char");
So adjust the class_create() function in driver to fix the above problem due
to kernel code change.

cet_ioctl.c: update the the code for new driver format

---

README.md
tdx-compliance/tests

README.md: Refine the README Add More Features Links
tdx-compliance: Add tests file

Refine the Readme and add tests for tdx-compliance

---

workload-xsave/yogini.c

1. A logic error caused the program to not run properly and has been fixed.

workload-xsave: yogini.c bug fix

---

topology/cpu_topology.sh

The grep command may give different format of output when the system has one node or multiple nodes.
one node system:
$ grep . /sys/devices/system/node/node*/cpulist
0-35
two nodes system:
$ grep . /sys/devices/system/node/node*/cpulist
/sys/devices/system/node/node0/cpulist:0-25,52-77
/sys/devices/system/node/node1/cpulist:26-51,78-103
If the system has only one node, subsequent code cannot parse noma_nodes correctly, causing wrong test result. Add -H option for grep command to unify the output format no matter how many nodes the system has.
== before fix ==
$ numa_nodes=$(grep . /sys/devices/system/node/node*/cpulist 2>&1) $ echo "$numa_nodes"
0-35
$ node_cpu_list=$(echo "$numa_nodes" | sed -n "1, 1p" | awk -F ":" '{print $2}') $ echo "$node_cpu_list"
<-- nothing
== after fix ==
$ …

cpu topology: fix numa_nodes format

---

pt/perf_tests.sh
pt/tests

Add test description for each case
Add acronyms decode
Add 5 new cases which were running with perf tool
Fix 1 script bug for event trace case
Add 7 C program designed cases into tests

Update Intel PT cases

---

tdx-guest/tdx_attest_test_suite/Makefile
tdx-guest/tdx_attest_test_suite/tdx-attest-test.c

compile test source code based on kernel header tdx-guest.h define to adapt to difference version of tdx guest kernel under test
[Test Components] tdx
[Test Types] func

[tdx-guest] Test Enhance: compile based on kernel header define

---

cstate/tests-client
cstate/tests-server
pstate/tests
thermal/thermal-tests
topology/tests-client
topology/tests-server

cstate/pstate/topology/thermal are legacy features Which do not need depend`ency check

Update dependency for cstate/pstate/topology/thermal

---

runtests

Other apps like avocado could use target feature dependence exit number to judge if test platform supports this feature, so add this dependence check exit number for the platform dependence result.

runtests: add dependence check exit number

---

BM/tdx-guest/tdx_mem_test.sh

for unknown reason on TDX upstream R&D setup environment, several mem accept full mem consumed time increased, revise baseline data based on that, confirmed as non-kernel performance regression but test environment changing introduced
[Test Components] tdx-guest
[Test Types] func

[tdx-guest] Test Enhance: update mem accept baseline

---

.github/scripts/cfg-lint-check.py
.github/scripts/requirements-ci.txt
.github/workflows/pull_request.yml

Check the python code and cfg code in KVM, to align the code style with Avocado.
Signed-off-by: Xudong Hao <xudong.hao@intel.com>

Enable github PR python pre-check for KVM

---

BM/ifs/README.md

Add more description and usage information in ifs README.md.

ifs: add more description and usage in ifs README.md

---

.github/scripts/pr_check

Can't follow non-constant source. Use a directive to specify location.
From the shellcheck document 1090:
ShellCheck is not able to include sourced files from paths that are determined at runtime. The file will not be read, potentially resulting in warnings about unassigned variables and similar.
It more likes the limitation of shellcheck, but not the source code, disable it.

Action: Ignore the shell rule 1090

---

BM/tdx-guest/tdx_dep_check.sh
BM/tdx-guest/tests

add TDX dependency check before run any tdx-guest test
[Test Components] tdx-guest

[BM] [tdx-guest] Test Enhance: add TDX dependency check

---

BM/runtests

As before runtests could only support tests-client and tests-server, now it could support tests-guest/tests-gnr/tests-spr and so on test files.

runtests: add tests-guest/tests-gnr/tests-spr support

---

BM/ifs/ifs_common.sh

Fix one warning in ifs_common.sh: "grep: warning: stray \ before ,".

ifs: fix one warning in ifs_common.sh

---

KVM/qemu/td_huge_resource.cfg
KVM/qemu/tests/td_huge_resource.py

Allocate half of online CPUs to TDVM, half of availiable memory resource to TDVM, check if TD can boot up.

Add TDX huge resource test case

---

BM/amx/README.md
BM/amx/tmul/Makefile
BM/amx/tmul/tmul.c

add amx_fp16 support based on gcc version, gcc 13.3 or higher will include amx_fp16 test support, otherwise bypass it since gcc don't support it likely and test code compile will fail
[Test Components] amx/tmul

[BM] [amx] Test Enhance: add amx_fp16 test support based on gcc version

---

BM/tools/pcie/.gitignore
BM/tools/pcie/Makefile
BM/tools/pcie/pcie_check.c

The pcie_check tool can quickly verify specific PCI/PCIe capabilities at specified offset bytes and specific bit sizes, without being restricted by the version limitations of the lspci tool.

pcie_check: add the pci/pcie register check followed the PCIe spec.

---

BM/amx/tests
scenario/gnr-oe/tests-amx

add 43 amx TCs for opensource purpose, including gnr-oe support scenario
[Test Components] amx

[LKVS] [AMX] New Test: add 43 amx TCs for opensource purpose

---

BM/tools/pcie/pcie_check.c

1. Fixed warning: suggest parentheses around ‘-’ in operand of ‘&’ [-Wparentheses]: if (width > 0 && width < 17 && (width & width - 1) == 0)
2. Removed unused result, nextpoint.

pcie_check: fix some pcie_check compilation warnings

---

BM/pcie/README.md
BM/pcie/pcie_check.sh
BM/pcie/tests

add 3 pcie capability TCs to cover gen4, gen5 and gen6 platform basic pcie check
[Test Components] pcie
[Test Types] bat

[lkvs] [pcie] New Test: add 3 pcie capability TCs

---

BM/tdx-compliance/README.md
BM/tdx-compliance/tdx-compliance.c
BM/tdx-compliance/tdx-compliance.h
BM/tdx-compliance/tests-trigger-cpuid.sh

1. Use the kprobe method to capture the return value of handle_cpuid, and determine whether #VE or #GP is triggered based on the return value.
2. Also can modify the detection functions, such as hanlde_cpuid, read_msr, write_msr, handle_mmio, handle_io, etc. Only need to modify the value of .kp.symbol_name.

tdx-compliance: kprobe

---

BM/common/common.sh
BM/common/general_test.sh

check_module function can be used to check whether a module exists or can be loaded.
Example usage:
./general_test.sh -t module -p einj
Example output:
|0715_165104.347|TRACE|Module einj is already loaded|

general_test: add the module existence/load check function

---

BM/cstate/powermgr_cstate_tests.sh
BM/cstate/tests-server

Add turbo freq case with all the cstate default state Remove residency latency override case as mainline kernel does not support

Add turbo freq case with all the cstate default state

---

BM/README.md
BM/tpm/.gitignore
BM/tpm/README.md
BM/tpm/test_async.sh
BM/tpm/test_smoke.sh
BM/tpm/test_space.sh
BM/tpm/tests
BM/tpm/tpm2.py
BM/tpm/tpm2_tests.py

It includes tpm smoke, content, async 15 test cases from kself-test and marked in the code file header.
In order to be compatible and executed under LKVS, some compatibility adjustments like PYTHONPATH have been made.

BM/tpm: add 15 tpm test cases

---

BM/guest-test/qemu.config.json

update -no-hpet based on QEMU change
[Test Components] guest-test

[lkvs] [guest-test] Bug Fix: update -no-hpet to -machine q35,hpet=off

---

KVM/qemu/td_huge_resource.cfg
KVM/qemu/tests/td_huge_resource.py

Case 1: boot one TD with maximum vcpus number
Caes 2: boot one TD with out of maximum vcpus number, expect fail to boot.

TDX: Add one max vcpus test case and one negative case

---

KVM/qemu/tdx_max_guests.cfg
KVM/qemu/tests/tdx_max_guests.py

Case1: Boot maximum number of TDs
Case2: Boot maximum+1 number of TDs, expect the last TD booting fail.

TDX: Add 2 test cases with maximum number of TD booting

---

scenario/spr-oe/tests-dsa1

spr-oe: add spr-oe scenario

---

scenario/spr-oe/tests-ifs

The function need customers provide blob files, which blocks the all function tests.

spr-oe: Remove some functional tests for IFS

---

KVM/qemu/tests/x86_cpuid.py
KVM/qemu/x86_cpuid.cfg

Add 13 New Instrcutions cpuid check test cases for both TDVM and VM.

KVM: Enable cpuid check in VM and adds NIs test cases

---

BM/runtests

In some case, users don't want to check the dependence. They guarantee the execution environment.

runtests: Add option to skip dependence check

---

BM/tools/cpuid_check/cpuid_check.c

Add the multi bits output value check function, for example: ./cpuid_check  1 0 0 0 a 4:7 5
Suggested-by: Xudong Hao <xudong.hao@intel.com>

cpuid_check: add the multi bits output value check function

---

KVM/qemu/boot_check.cfg
KVM/qemu/x86_cpu_flags.cfg

So that all TD cases can be run with simple description. For example: x86_cpu_flags.tdvm

KVM: update some test cases name

---

BM/telemetry/telemetry_tests.sh
BM/telemetry/tests
scenario/emr-oe/tests-telemetry
scenario/spr-oe/tests-telemetry
scenario/srf-oe/tests-telemetry

Which will be covered in intel_tpmi cases

Remove intel_vsec check from telemetry tests

---

BM/workload-xsave/start_test.sh

This patch is to fix the following issue:
cd workload-xsave/build
../start_test.sh -1 100 AMX memcpy MEM SSE RDTSC UMWAIT TPAUSE PAUSE DOTPROD AVX512 AVX2 AVX
trace-cmd record -e x86_fpu -F ./yogini -b 1 -r 100 -w AMX -w memcpy -w MEM -w SSE -w RDTSC -w UMWAIT -w TPAUSE -w PAUSE -w DOTPROD -w AVX512 -w AVX2 -w AVX usage: ./yogini [OPTIONS]
./yogini runs some simple micro workloads
-w, --workload [workload_name,threads#,break#, ...]
Available workloads:  AMX memcpy MEM SSE RDTSC UMWAIT TPAUSE PAUSE DOTPROD AVX512
AVX2 AVX
-r, --repeat, each instance needs to be run
-b, --break_reason, [yield/sleep/trap/signal/futex]
For more help, see README

BM: fix the issue of yogini parameter error

---

BM/tdx-guest/tdx_speed_test.sh

in corner case, server ID return trimed value still has leading whitespace, remove such potential leading and trailing whitespace for correct server target operation
[Test Components] tdx-guest
[Test Types] func

[tdx-guest] Bug Fix: remove potential whitespace in server ID

---

BM/cet/cet_driver/cet_ioctl.c

Unload cet_ioctl driver will meet BUG as following: "
[  203.429071] Will unload driver.
[  203.429076] Class pointer 'cl' is valid: 000000002a4ca71a, *cl:000000002a4ca71a [  203.429078] Device pointer 'dev' is valid &dev:0000000045468ace, dev:532676608 [  203.429244] BUG: unable to handle page fault for address: ffffc9000447fbd4 [  203.429247] #PF: supervisor read access in kernel mode [  203.429248] #PF: error_code(0x0000) - not-present page [  203.429249] PGD 100000067 P4D 100000067 PUD 100285067 PMD 126d0b067 PTE 0 [  203.429253] Oops: 0000 [#1] PREEMPT SMP NOPTI
[  203.429256] CPU: 8 PID: 4469 Comm: rmmod Tainted: G           O       6.7.0-rc7-asymmetric5+ #15
[  203.429258] Hardware name: Gigabyte Technology Co., Ltd. X299 UD4 Pro/X299 UD4 Pro-CF, BIOS F8a 04/27/2021
[  203.429259] …

cet_ioctl: fix one BUG issue after unload cet_ioctl driver

---

BM/tools/pcie/pcie_check.c

Will continue instead of return if PCI cap is 0xff. Add more description info for pcie check.
Reported-by: Yi Lai <yi1.lai@intel.com>

pcie_check: will continue instead of return if PCI cap is 0xff

---

BM/lam/Makefile
BM/lam/README.md
BM/lam/lam.c
BM/lam/tests
scenario/srf-oe/tests-lam

added 8 test cases for LAM BM on SRF platform.
lam -t 0x1    # malloc
lam -t 0x2    # max_bits
lam -t 0x4    # mmap
lam -t 0x8    # syscall
lam -t 0x10   # io_uring
lam -t 0x20   # inherit
lam -t 0x40   # pasid
lam -t 0x80   # cpuid

add LAM basic test cases on SRF platform

---

KVM/qemu/tdx_basic.cfg
KVM/qemu/tests/tdx_basic.py

Check host environment firstly, then try to boot TD.

KVM: Update the TDX basic test case

---

BM/CMakeLists.txt
BM/amx/tmul/CMakeLists.txt
BM/avx512vbmi/CMakeLists.txt
BM/cet/CMakeLists.txt
BM/cmpccxadd/CMakeLists.txt
BM/pt/CMakeLists.txt
BM/splitlock/CMakeLists.txt
BM/telemetry/CMakeLists.txt
BM/th/CMakeLists.txt
BM/tools/cpuid_check/CMakeLists.txt
BM/tools/pcie/CMakeLists.txt
BM/umip/CMakeLists.txt
BM/workload-xsave/CMakeLists.txt
BM/xsave/CMakeLists.txt

1. This commit introduces CMakeLists.txt files across the BM and its subdirectories: amx/tmul avx512vbmi cet cmpccxadd pt splitlock telemetry th tools/cpuid_check tools/pcie umip xsave. Each CMakeLists.txt is configured to build the corresponding component of the project.
2. For amx/tmul and avx512vbmi, instruction set detection has been added to the CMakeLists.txt. If the target CPU does not support the corresponding instruction sets, the build will be skipped.
3. For features such as cet, umip, pt, etc., specific checks have also been added to the CMakeLists.txt. If necessary files or kernel modules are missing, the build will be skipped.
4. The installation process has been updated. You can now create a build directory within the BM directory, configure the project with CMake, compile …

BM: Add CMake build support

---

BM/instruction-check/auto_gen_test.py
BM/instruction-check/feature_list.py
BM/instruction-check/instruction_check.py

Depending on the platform, different test cases are executed now and some other optimizations to enhance the robustness of the code.

instruction_check: enhancement

---

BM/lass/README.md
BM/lass/tests
KVM/qemu/feature_test.cfg

add lam and lass test cases for KVM.
- test cases as feature function checking 
- run lam.c in KVM guest to check function of lam
- run lass.c in KVM to guest check function of lass

add KVM test for lam and lass

---

BM/instruction-check/feature_list.py

vpclmulqdq is introduced by Intel Icelake server platform.

instruction_check: Add vpclmulqdq cpuid

---

KVM/qemu/tdx_disable.cfg
KVM/qemu/tests/tdx_disable.py

tdx_disable.ept
tdx_disable.tdx

KVM: rename TDX disable ept case and add disable tdx test case

---

BM/dma/dma_test.sh
BM/dma/tests

Make use of DSA and module dmatest to do DMA tests. User have to build module dmatest as a module, and enable idxd device.

Add tests for dma using DSA

---

KVM/qemu/tests/vfio_gpu_boot.py

The time for cuda test depends on the performance of host, to support more platforms, we increase the timeout for this case.

Increase timeout for cuda test in guest with GPU passthorugh

---

BM/pcie/pcie_check.sh
BM/tdx-guest/tdx_dep_check.sh

Fix the 'test_print_wrn' to 'test_print_wrg'.

BM: Fix test_print_wrg typo

---

BM/tdx-host/qemu_dpamt.sh
BM/tdx-host/qemu_legacy.sh
BM/tdx-host/tdx_dep_check.sh
BM/tdx-host/tdx_dpamt_test.sh
BM/tdx-host/tests

TDX dynamic pamt is a new TDX feature to support VMM to allocate PAMT_4K dynamically when there is TDVM launched, and reclaim all pages in a contiguous area when TDVM is gone, to reduce static PAMT 4K pages allocation consumption on system memory.
This test implementation cover all functional and stress testing of dynamic pamt allocation implemented in current Linux Kernel RFC patch series https://lore.kernel.org/all/20250609191340.2051741-1-kirill.shutemov@linux.intel.com/

New Test: add 14 TCs to cover TDX dynamic pamt feature

---

BM/tdx-compliance/tdx-compliance-main.c

When run tdx compliance CPUID cases, if with CONFIG_DEBUG_PREEMPT set in kernel config, guest Call Trace:
[  161.254208] Call Trace:
[  161.254211]  <TASK>
[  161.254214]  dump_stack_lvl+0x4b/0x70
[  161.254218]  check_preemption_disabled+0xd6/0xe0 [  161.254223]  run_cpuid.isra.0+0x11/0x70 [tdx_compliance] [  161.254227]  run_all_cpuid.isra.0+0xf7/0x1b9 [tdx_compliance] [  161.254229]  tdx_tests_proc_write.cold+0xa7/0x107 [tdx_compliance] [  161.254231]  full_proxy_write+0x59/0xa0
[  161.254236]  vfs_write+0xea/0x440
[  161.254239]  ? preempt_count_add+0x4b/0xa0
[  161.254242]  ? fput+0x34/0x190
[  161.254243]  ? filp_close+0x1d/0x30
[  161.254246]  ? do_dup2+0xae/0x150
[  161.254249]  ksys_write+0x6a/0xe0
[  161.254251]  do_syscall_64+0x54/0x110
[  161.254254] …

tdx-compliance: Fix kernel Call Trace about check_preemption

---

BM/amx/Makefile
BM/amx/README.md
BM/amx/tests
BM/amx/tests-stress

update default compile target to adapt to different gcc version, update tests contents accordingly

update default compile target and tests contents
