- cet/.gitignore
- cet/Makefile
- cet/README.md
- cet/quick_test.c
- cet/shstk_alloc.c
- cet/shstk_huge_page.c
- cet/test_shadow_stack.c
- cet/wrss.c
Control-flow Enforcement Technology(CET) is a security feature in Intel Processors. The 11th generation and later Intel CPUs will support the CET feature.
CET is the best method to prevent ROP/JOP attack from the root cause (instruction level) from compatibility and performance perspective.
CET contains 2 parts of functions: shadow stack(SHSTK) and indirect branch tracking(IBT).
1. Shadow Stack – return address protection to defend against Return Oriented Programming(ROP),
2. Indirect Branch Tracking – free branch protection to defend against Jump/Call Oriented Programming(JOP).
Only userspace SHSTK cases will be provided in this commit. For specific cases, please check the README.md in cet folder. Userspace IBT cases will be provided in the future. …
> CET test: Initial version for CET user space SHSTK test.

- README.md
> README.md: fix typo gold -> goal

- common/common.sh
1. Remove *skipt_test* function from shell library.
2. Remove *runtest* and releated functions from shell library.
3. Introduce *last_dmesg_timestamp* and extract_case_dmesg* functions. These 2 functions can be used in combination to obtain dmesg generated during test execution. following code block illustrate how the 2 functions work together:
```sh
last_dmesg_timestamp
...
extract_case_dmesg | grep "$pattern" 
```
> common/common.sh: update shell library

- cet/quick_test.c
- cet/shstk_alloc.c
- cet/shstk_huge_page.c
> CET: add Glibc not supported judgement for SHSTK enabled by Glibc code

- xsave/tests
> xsave tests: add xsave test items into tests

- umip/tests
> umip tests: add umip test items in tests

- cet/shstk_cp.c
> shstk_cp.c: fix "don't use multiple blank lines" problem

- .github/workflows/pull_request.yml
> enable GitHub pull request prechecking

- .github/workflows/pull_request.yml
pr_check is put in /bin directory.
Refer to: https://github.com/hanning0511/lkvs-pr-check/blob/master/Dockerfile
> fix wrong path of pull request checking script

- pt/.gitignore
- pt/Makefile
- pt/README.md
- pt/branch.c
- pt/cpl.c
- pt/negative_test.c
- pt/nonroot_test.c
- pt/psb.c
- pt/utils.c
- pt/utils.h
Signed-off-by: ammy.yi@intel.com <ammy.yi@intel.com>
> PT test: Add 5 PT cases.

- CONTRIBUTING.md
Including coding rules, information format, and check patch.
> CONTRIBUTING.md: Add development rule in the CONTRIBUTING.md

- isst/README.md
- isst/intel_sst.sh
- isst/tests
Signed-off-by: Wendy Wang <wendy.wang@intel.com>
> Add isst test cases

- runtests
> runtests: remove wrong comment and fix shellcheck issue

- .github/scripts/pr_check
- .github/workflows/pull_request.yml
> .github: integrate pull request checking code into repo

- .github/scripts/pr_check
- Add `--fix` for checkpatch.pl. If errors or warnings found, show the experimental fixes in checking log.
- Instead of quiting checking script on first taint, now the script will collect all taints before quiting.
- Optimize output format.
> pr_check: refine pull request checking script

- README.md
Remove the TO-DO list which has been completed after last release. Add usage of new test runner runtests.
> Readme.md: Refine the Readme.

- pt/branch.c
- pt/cpl.c
- pt/nonroot_test.c
- pt/psb.c
- pt/utils.c
- pt/utils.h
Signed-off-by: Ammy Yi <ammy.yi@intel.com>
> Fix warning for PT build.

- pmu/README.md
- pmu/apebs_tests.sh
- pmu/pmu_tests.sh
- pmu/tests
Signed-off-by: Ammy Yi <ammy.yi@intel.com>
> Add 17 PMU test cases.

- pt/README.md
- pt/perf_tests.sh
- pt/tests
Signed-off-by: Ammy Yi <ammy.yi@intel.com>
> PT test: Add 20 PT cases with perf tool.

- rapl/README.md
- rapl/intel_rapl_test.sh
- rapl/tests-client
- rapl/tests-server
Signed-off-by: Wendy Wang <wendy.wang@intel.com>
> Add Intel_RAPL driver related test cases

- common/common.sh
> common.sh: Fix some formatting issues reported by shellcheck

- .github/scripts/pr_check
> .github/scripts/pr_check: ignore SC2013 when performing shellcheck

- common/uname
Add a fake uname to cheat the Makefile to use docker fs related kernel version.
> common: Add a fake uname tool

- .github/workflows/pull_request.yml
> .github/workflows/pull_request.yml: enable build checking

- README.md
Add two particular ways for Intel PT and CET.
> README.md: Solve the dependency for local compiling.

- .github/scripts/build_check
- .github/workflows/pull_request.yml
> .github: refine build check, check build warnings

- thermal/README.md
- thermal/thermal-tests
- thermal/thermal_test.sh
Signed-off-by: Wendy Wang <wendy.wang@intel.com>
> Add x86_pkg_temp thermal two cases

- fred/Makefile
- fred/fred_test_driver.c
Add a test kernel module to operate some registers.
> Add fred test kernel driver

- cet/test_shadow_stack.c
Chen Farrah found the stuck issue when execute the test_shadow_stack several times in test.
Rick has fixed this test code issue, debug code for issue reproduce is also added for issue debug.
> test_shadow_stack.c: fix wrssq 0x12345678 to ptr stuck with read issue.

- tdx-compliance/tdx-compliance.c
> Fix: fix condition of check_restuls_cr

- tdx-compliance/tdx-compliance-msr.h
> Add pre_condition for related cases.

- README.md
- ifs/README.md
- ifs/ifs_common.sh
- ifs/ifs_tests.sh
- ifs/tests
Add 7 ifs 0 mode function test cases.
> ifs: add 7 ifs 0 mode function test cases

- workload-xsave/.gitignore
- workload-xsave/Makefile
- workload-xsave/README.md
- workload-xsave/run_common.c
- workload-xsave/start_test.sh
- workload-xsave/work_AMX.c
- workload-xsave/work_AVX.c
- workload-xsave/work_AVX2.c
- workload-xsave/work_AVX512.c
- workload-xsave/work_DOTPROD.c
- workload-xsave/work_GETCPU.c
- workload-xsave/work_MEM.c
- workload-xsave/work_PAUSE.c
- workload-xsave/work_RDTSC.c
- workload-xsave/work_SSE.c
- workload-xsave/work_TPAUSE.c
- workload-xsave/work_UMWAIT.c
- workload-xsave/work_VNNI.c
- workload-xsave/work_VNNI512.c
- workload-xsave/work_memcpy.c
- workload-xsave/worker_init4.c
- workload-xsave/worker_init_amx.c
- workload-xsave/worker_init_avx.c
- workload-xsave/worker_init_avx2.c
- workload-xsave/worker_init_dotprod.c
- workload-xsave/worker_init_sse.c
- workload-xsave/yogini.c
- workload-xsave/yogini.h
Implement a series of micro workloads to experience the functionality of xsave/xrestore in user space. These micro benchmarks are valuable for performance tuning and debugging purposes.
> Initialize workload of xsave.

- runtests
Hightlight the results columns making it easy to identify by external test frameworks.
> runtests: Add prefix and highlight the data

- README.md
- workload-xsave/work_AVX2.c
- workload-xsave/work_AVX512.c
- workload-xsave/work_DOTPROD.c
- workload-xsave/work_VNNI.c
- workload-xsave/work_VNNI512.c
- workload-xsave/worker_init_avx2.c
- workload-xsave/worker_init_dotprod.c
> pull request

- .github/workflows/pull_request.yml
Add line
permissions: read-all
> workflows: Fix pull_request.yml to pass OpenSSF check

- guest-test/tdx/README.md
- guest-test/tdx/tdx.test_executor.sh
- guest-test/tdx/tdx_device_filter_test.sh
- guest-test/tdx/tests
add 3 TCs to cover basic TDX guest device filter functional check
[Test Components] tdx
[Test Types] func
> [guest-test] [tdx] New Test: add 3 TDX device filter TCs

- telemetry/.gitignore
- telemetry/Makefile
- telemetry/README.md
- telemetry/telemetry_tests.c
- telemetry/telemetry_tests.sh
- telemetry/tests
check if telemetry sysfs is generated
check if telemetry device is generated
check if detailed telemetry sysfs value is correct check if telemetry data is readable
check if pci drvier loaded
check load/unload telemetry drvier
check load/unload telemetry pci drvier with 32bit binary check load/unload telemetry pci drvier
> Add 8 telemetry cases

- README.md
Clarify the rules for naming features, tests, etc.
> Readme: Refine Contribution Guidelines.

- KVM/qemu/provider/cpu_utils.py
- KVM/qemu/tdx_basic.cfg
- KVM/qemu/tests/tdx_basic.py
The 1st TDX test case for basic check:
1. Check if platform host support TDX
2. Boot one TDVM
3. Check TDX cpu flag in TDVM
> Add one TDX basic test case

- .github/scripts/build_check
Update the path of the BM due to the change of code folder.
> github-action: Update BM code path

- BM/edac/README.md
- BM/edac/intel_edac.sh
- BM/edac/tests
Intel i10nm EDAC driver supports the Intel 10nm series server integrated memory controller. Introduce this feature into lkvs test suite and add 2 test cases.
> edac: introduce edac feature into lkvs

- BM/README.md
- BM/cmpccxadd/.vscode/settings.json
- BM/prefetchi/Makefile
- BM/prefetchi/README.md
- BM/prefetchi/prefetchi.c
- README.md
> prefetchi: add 1 BAT case

- .github/scripts/cfg-lint-check.py
- KVM/qemu/td_disable_ept.cfg
- KVM/qemu/tests/td_disable_ept.py
TDVM should be not launched while disable EPT
> Add TDX with EPT disable test case

- BM/telemetry/Makefile
- BM/telemetry/telemetry_tests.sh
- BM/telemetry/tests
> Update telemetry case

- BM/common/load_unload_module.sh
- BM/telemetry/telemetry_tests.sh
Update module-unload-load func
Remove pem driver module from telemetry case
> Update module-unload-load func

- BM/pmu/pmu_iommu_tests.sh
Add a test script for the pmu iommu test.
> Add the test script for the pmu iommu test.

- BM/pmu/tests
> Removed the duplicated cases.

- scenario/README.md
- scenario/gnr-oe/tests-iax
The scenario folder holding tests files which are specified for some scenario, such as tests for GNR with OpenEuler OS.
Add tests-iax as an example.
> Add scenario folder

- BM/ufs/tpmi_ufs.sh
> Update UFS case to fix a bug

- KVM/qemu/td_boot_multimes.cfg
- KVM/qemu/tests/td_boot_multimes.py
td_boot_multimes.one_socket.one_cpu
td_boot_multimes.one_socket.four_cpu
td_boot_multimes.two_socket.four_cpu
> Add 3 TDX cases by booting TD several times

- scenario/emr-oa/README.md
- scenario/emr-oe/README.md
Add new scenario files for EMR for OpenEuler and Anolis OS.
> Add scenario file for EMR platform

- BM/Avocado-run.py
Add tests that use avocado to execute BM. Now can use the Avocado test framework to run bare metal tests.
> Avocado-run

- BM/dsa/dsa_user_test.sh
- BM/dsa/iax_user_test.sh
- BM/dsa/tests-dsa1
- BM/dsa/tests-dsa2
- BM/dsa/tests-iax
- scenario/emr-oe/tests-dsa1
- scenario/emr-oe/tests-iax
- scenario/gnr-oe/tests-dsa1
idxd: Add tests file for GNR and EMR
> idxd: Add tests file for GNR and EMR 

- BM/runtests.py
In runtests.py, check the dependency, if the exit value is not 0, then terminate the test.
> Add the dependency check

- BM/runtests.py
> runtests.py: bug fix

- KVM/qemu/multi_vms.cfg
- KVM/qemu/tests/boot.py
1. 1 TDVM and 1 VM co-exist
2. 2 TDVM
3. 2 VM
4. 4 VM
> Add 4 cases of multiple VMs boot

- KVM/qemu/tests/x86_cpu_flags.py
- KVM/qemu/x86_cpu_flags.cfg
x86_cpu_flags.tsc_deadline.default.tdvm
x86_cpu_flags.tsc_deadline.disable.tdvm
x86_cpu_flags.tsc_deadline.default.vm
x86_cpu_flags.tsc_deadline.disable.vm
> Add 4 test cases to test TSC deadline cpu flag

- scenario/emr-oa/tests-amx
- scenario/emr-oe/tests-amx
simplify amx testcases configuration, to reduce amx functional test execution time
[Test Components] amx
> [lkvs] [amx] Test Enhance: simplify test scenarios to reduce test time

- KVM/qemu/boot_check.cfg
- KVM/qemu/tests/boot_check.py
Various vcpus and memory configure to boot VM
> Add 24 TDX test cases and 24 No-TD test cases

- KVM/qemu/multi_vms.cfg
2 VM co-existing with various vcpus and memory configure.
> Add 10 TDX cases and 4 Non-TDX test cases

- scenario/spr-oe/README.md
- scenario/spr-oe/tests-amx
- scenario/spr-oe/tests-cstate
- scenario/spr-oe/tests-iax
- scenario/spr-oe/tests-pmu
- scenario/spr-oe/tests-pstate
- scenario/spr-oe/tests-rapl
- scenario/spr-oe/tests-telemetry
- scenario/spr-oe/tests-topology
Take EMR as a base, then modify some tests.
> spr-oe: Add tests file for spr platform

- KVM/qemu/tests/tdx_max_guests.py
- KVM/qemu/tests/tsc_freq.py
- KVM/qemu/tests/x86_cpuid.py
Remove yum/rpm etc and use common utils_package.
> KVM: enable Debian package manage for test cases

- BM/runtests.py
Specify the value of the identifier field, and the executed command will now be used as the name of test.
> runtest.py: enhancement

- KVM/qemu/feature_test.cfg
- KVM/qemu/x86_cpu_flags.cfg
- KVM/qemu/x86_cpuid.cfg
1 CPUID test
2 CPU flags tests
1 functionality test
> KVM: Add 4 UMIP test cases for TD and Non-TD VM

- BM/instruction-check/feature_list.py
- KVM/qemu/x86_cpu_flags.cfg
- KVM/qemu/x86_cpuid.cfg
check CPUID and flags for lam and lass
> add cpu info check for lam lass

- BM/instruction-check/feature_list.py
- KVM/qemu/x86_cpu_flags.cfg
- KVM/qemu/x86_cpuid.cfg
3 mwait test cases for TD
3 mwait test cases for Non-TD
Also add MWAIT/MONITOR in instruction-check
> KVM: Add MWAIT/MONITOR test cases

- BM/pmu/pmu_tests.sh
> Del nmi_watchdog setting for pmu_test.sh which was not used

- BM/tdx-guest/tdx.guest_test_executor.sh
- BM/tdx-guest/tests
- BM/tdx-guest/vm_kdump_test_entry.sh
- BM/tdx-guest/vm_kexec_test.sh
- BM/tdx-guest/vm_kexec_test_entry.sh
9 new TCs of VM guest kdump functional test
11 new TCs of VM guest kexec functional test
mainly used as cross check reference of same configuration TD VM test scenarios
> [LKVS] [guest-test] New Test: add 21 new TCs of VM guest kdump and kexec

- BM/instruction-check/feature_list.py
- KVM/qemu/x86_cpuid.cfg
AVX512F AVX512DQ AVX512BW AVX512CD AVX512VL are introduced by Intel Skylake server platform.
> instruction_check: Add Skylake AVX512 cpuid

- BM/amx/tests-stress
Create a new tests file for stress tests.
> AMX: split stress test and functional tests

- BM/adaptation/debian/Dockerfile.build
- BM/adaptation/debian/packages
Clone and build idxd-config and dsa_test/iax_test
Clone and build intel-speed-select tool
Clone and build turbostat
> BM: adaptation: Add idxd and iss tool build

- BM/dsa/README.md
Add the requirements of BIOS, Kernel configure and Kernel command line for DSA tests.
> DSA: Refine the Readme adding pre-conditions

- BM/thermal/thermal_test.sh
The stress will be killed very soon before getting correct results. Add a period of sleep.
> thermal: Add a proper sleep time

- BM/ifs/README.md
Refine the steps of the environment setup.
Supplement kernel configs.
> BM: ifs: Fix README

- BM/tdx-compliance/tdx-compliance-cpuid.h
> tdx-compliance: Update CPUID cases according to the updates in qemu and VE reduction spec

- BM/tdx-compliance/tdx-compliance-cpuid.h
which is updated and covered by VE reduction
> tdx-compliance: Remove some old CPUID cases
